.pre-commit-config.yaml
src/lsst/cm/tools/core/butler_utils.py
src/lsst/cm/tools/db/handler_utils.py
src/lsst/cm/tools/db/sqlalch_interface.py
tests/test_db_id.py
tests/test_sql_interface.py

- Fixes to `.pre-commit-config.yaml` to work around gitlab auth issue and "Poetry configuration is invalid" issue
- Update other pre-commit hook versions to latest while we're here
- Source reformat by new version of black (no longer likes blank lines after function `def`s apparently)

pre-commit hook fixes

---

src/lsst/cm/tools/cli/commands.py
src/lsst/cm/tools/cli/options.py
src/lsst/cm/tools/core/panda_utils.py

I even made a JIRA ticket and everything.

Minor changes to get panda-query related command line tasks working

---

src/lsst/cm/tools/core/error_code_decisions.yaml
src/lsst/cm/tools/core/panda_utils.py
src/lsst/cm/tools/db/sqlalch_interface.py

This PR finishes the work of ticket 36837 in pulling all data from PanDA into the decision workflow and prepares for two main additions:
1) adding the pulled error data to the error instance database
2) making a decision engine based on comparing pulled error data against the error types database

Update ticket 36837

---

src/lsst/cm/tools/cli/commands.py
src/lsst/cm/tools/cli/options.py
src/lsst/cm/tools/core/db_interface.py
src/lsst/cm/tools/db/error_table.py
src/lsst/cm/tools/db/sqlalch_interface.py

This wraps up the work in ErrorType and ErrorInstance for dealing with error reporting in the command line with cm tools.

Finish implementing ErrorType and ErrorInstance for matching and reporting errors

---

src/lsst/cm/tools/core/error_code_decisions.yaml

No new errors came up on this run, so it's just adding the Jira ticket number to the ones that we did see.

Updated to include errors from w_2023_01 on HSC-RC2

---

src/lsst/cm/tools/db/step_handler.py

We need this to split tract-splittable steps into tracts

Update StepHandler to check split_vals for explicit group splitting

---

src/lsst/cm/tools/core/panda_utils.py

Addresses tickets 38021 and 38016 by fixing the logic engine (accounting for all possible jediTask statuses) and committing a statusEnum to the job.status.
I'm pretty sure the intended case is to set a completed job (all green lights in PanDA) to statusEnum.completed so that it still goes through the validation, but I would like conformation from Eric on this fact.

implemented update to job status

---

src/lsst/cm/tools/db/error_table.py

Trivial changes to increase length of diagnostic message printed for ErrorType and ErrorInstance objects

increase error_type and error_instance printouts

---

src/lsst/cm/tools/core/error_code_decisions.yaml

Since I did not pilot this run, @hsinfang would you mind looking over the entries from this run? I am particularly concerned with whether the new errors have been marked as resolved and if it turned out I missed which ones were infrastructure errors. Thanks!

Added errors from w_2023_03 run on HSC-RC2/DM-37570

---

src/lsst/cm/tools/db/job_handler.py

fix name of custom_lsst_setup variable

---

src/lsst/cm/tools/core/panda_utils.py

Pretty quick fix, just replacing a lingering 'completed' with a 'done'.

fixed bug in logic tree where done was not properly handled

---

src/lsst/cm/tools/db/sqlalch_interface.py

Also makes the error reporting more descriptive!

modified error reporting to not truncate unknown errors

---

src/lsst/cm/tools/db/job_handler.py

Turns out, all the changes I needed to get Weekly 11 running are changes I also need for all of the other stuff I might do. I'm hoping to merge to main so I can have different processing runs happening on different ticket branches so nothing production-specific gets tangled.

Pulling in changes that I also need to use for DM-37572

---

src/lsst/cm/tools/core/utils.py

Just a quick doc change of utils.py

---

src/lsst/cm/tools/core/panda_utils.py
src/lsst/cm/tools/db/sqlalch_interface.py

I just wrote a better way of processing the jobName that will get pipetask more consistently regardless of formating changes.

more complicated string processing to avoid misreading pipetask

---

src/lsst/cm/tools/db/sqlalch_interface.py

one line fix to use None instead of string

---

src/lsst/cm/tools/db/sqlalch_interface.py
src/lsst/cm/tools/db/step_handler.py

These changes were necessary for the HSC-RC2 w_2023_15 reprocessing

DM-38691: Reprocess HSC-RC2 with CM tools and w_2023_15

---

src/lsst/cm/tools/cli/options.py
src/lsst/cm/tools/core/butler_utils.py
src/lsst/cm/tools/core/db_interface.py
src/lsst/cm/tools/core/panda_utils.py
src/lsst/cm/tools/core/script_utils.py
src/lsst/cm/tools/db/error_table.py
src/lsst/cm/tools/db/handler_utils.py
src/lsst/cm/tools/db/sqlalch_interface.py

This branch fixes a statusEnum referencing pipelines after errorType has been made to consistently refer to payload.

fixed lingering statusEnum still referencing pipelines

---

src/lsst/cm/tools/core/panda_utils.py

Fixed the logic on this check so that it would actually do what we want!

DM-40687: Fix to correctly return pipetask name

---

src/lsst/cm/tools/core/panda_utils.py

Quick one line fix to address a missing connection status check.

fixed incorrect connection error handling
